### ISSUE TITLE
ponowna wysyłka maili do odbiorców wypisanych

### ISSUE THREAD

**Issue by pomocFM** [SnowdogApps/FreshMail#1]
Hej, 

Klient zgłasza problem z wypisywaniem adresów z newslettera. 

Przykładowo:

adres example@example.com wypisał sie w kampanii o nazwie : „Mamy dla Ciebie rabat. Skorzystaj z 10% zniżki na Emu i odbierz metalową butelkę z prezencie! EmuXWaterAid”.
 

hash : tzzkxznxu0

Następnie otrzymał kolejny newsletter  „BLACK WEEKEND SALE do –75% Przesyłka i zwrot dla zamówień powyżej 100zł GRATIS!” ( hash: 8e62c0czlk ) mimo ze nie powinien.

Adres dodawany jest przez plugin magento i KLient twierdzi, że status adresu po wypisaniu nie jest aktualizowany właśnie po stronie Magento.

Będę wdzięczna za odpowiedź,
Ola

**Comment by dmaciej** [comment]
@pomocFM aktualizacja modułu do wersji 2.8.0 i skonfigurowanie [webhooków](https://github.com/SnowdogApps/FreshMail/blob/master/README.md#webhooks) powinno pomóc w tym problemie
