### ISSUE TITLE
Problem z integracją Magento

### ISSUE THREAD

**Issue by Agata345** [SnowdogApps/FreshMail#3]
Witam,

kiedy klient zakłada nowe konto w sklepie na Magento automatycznie wpada do bazy Freshmail jako kontakt "aktywny" nawet jeśli nie zaznaczył chęci otrzymywania newslettera. Pomimo tego, że w Magento nie ma go na liście subskrybentów newslettera to po synchronizacji list z poziomu Magento status we Freshmailu się nie zmienia. Zmieni się dopiero jak klient na swoim koncie włączy a następnie wyłączy newsletter (z poziomu administratora działa to podobnie). 
W poprzednim zadaniu wyczytałam, że jest w opcja w konfiguracji, gdzie należy włączyć "wymagane potwierdzenie" i wówczas kontakty nie będą automatycznie wpadać do Freshmail jako "aktywne" - niestety i tak wpadają. Zostało to przetestowane.

W jaki sposób ustawić konfigurację aby ze statusem "aktywne" wpadały tylko te kontakty, które wyrażają zgodę na otrzymywanie newslettera?

**Comment by dmaciej** [comment]
Moduł opiera się na liście subskrybentów z domyślnego modułu Magento. Nie ma możliwości , żeby do FreshMaila został wysłany e-mail, który nigdy nie przystąpił do subskrypcji. Prosiłbym o umieszczenie zrzutu ekranu z konfiguracji newslettera Magento oraz wskazanie dokładnej wersji modułu i samego Magento. Czy sklep używa multistore oraz innych modułów powiązanych z newsletterem?

**Comment by Agata345** [comment]
Dzień dobry,

Z racji tego, że konfiguracja systemu jest daną poufną, przesłałam zrzut ekranu mailowo na adres: kuba@snow.dog
Wersja Magento – 1.9
Wersja modułu Freshmail – tego nie mogę znaleźć, nie wiem
Sklep używa multistore, nie mamy innych modułów powiązanych z newsletterem

Dodatkowo – utworzyłam dwa konta testowe – jedno ze zgodą marketingową, drugie bez. Konto bez zgody wskoczyło do kolumny „do aktywacji”, czyli poprawnie. Teoretycznie powinien być mail systemowy z pytaniem o zgodę – jeśli klient zatwierdzi to wpada do aktywnych a jeśli nie potwierdzi to do nieaktywowanych.
Żadnej wiadomości systemowej nie dostałam.

Zrobiłam kampanię testową dla tych dwóch kontaktów (jeden ze zgodą, status aktywny, drugi „do aktywacji”) i pomimo braku jednej zgody kampania dotarła do obu kontaktów.
Co więcej… w zbiorze odbiorców do kampanii testowej oba kontakty mają status „aktywny” a w bazie głównej (która jest synchronizowana z Magento) jeden jako aktywny i jeden jako do aktywacji.
Dlaczego te informacje nie są spójne? Bazy powinny się wzajemnie synchronizować na poziomie FreshMail. Po to jest ta główna połączona z Magento.

**Comment by dmaciej** [comment]
@Agata345 z przesłanego zrzutu ekranu widać, że używasz starej wersji modułu, która nie jest wspierana (przynajmniej w obrębie tego repozytorium). Te moduły całkowicie różnią się od strony kodu.
Poniżej zrzut konfiguracji z wersji 2.x dla porównania:
![zrzut ekranu 2017-01-31 09 10 14](https://cloud.githubusercontent.com/assets/284649/22456900/684cf702-e795-11e6-8aad-ddd3d8fff9ed.png)
Zachęcamy do wymiany modułu i wtedy będziemy mogli ewentualnie służyć pomocą.

**Comment by Agata345** [comment]
Dziękuję za odpowiedź. Czyli powinniśmy zainstalować nową wersję? Czy ta z tego adresu jest aktualna? https://freshmail.pl/wtyczka/magento/

**Comment by mcjwsk** [comment]
Najlepiej pobrać najwyższą wersję ze strony https://github.com/SnowdogApps/FreshMail/releases gdyż na stronie FreahMail paczka jest aktualizowana z pewnym opóźnieniem. Standardowo proszę zweryfikować działanie najpierw w środowisku testowym.
