### ISSUE TITLE
Problem z konfiguracją pop-up'a oraz z synchronizacją danych

### ISSUE THREAD

**Issue by pomocFM** [SnowdogApps/FreshMail#4]
Cześć, będę wdzięczna za pomoc :) 

Klientka skarży się na następujący problem z popupem: 
1) brak przycisku dodaj listę w zakładce lista subskrypcji (prt screen w załaczeniu). Klientka dopytuje gdzie znajdzie informację do jakiej listy zapisuje pop-up. 
![screendla freshmail 1](https://user-images.githubusercontent.com/23213744/28020370-617b0e10-6584-11e7-8204-8028e7cf946e.jpg)

www sklepu klientki: sklep. nipplex.pl
Lista odbiorców nazywa się "nowa lipiec 2017".

Zgłasza też problem z synchronizacją: 
"Nie działa również synchronizacja. Wczoraj, wieczorem próbowałam zsynchronizować  i niestety wyświetlał się komunikat o błędzie."

Będę wdzięczna z odpowiedź, 
Karolina B.

**Comment by mcjwsk** [comment]
Ad. 1. Wybór listy jest możliwy po zmianie zakresu konfiguracji na konkretny sklep. Na załączonym zrzucie ekranu wybrany jest zakres domyślny, na którym te pole nie podlega konfiguracji.

Ad. 2. Pojawia się jakiś konkretny komunikat? Moduł posiada możliwość zapisywania logów (należy włączyć tę opcję najpierw w konfiguracji modułu), które mogą pomóc ustalić problem. Logi są zapisywane w pliku _var/log/snowfreshmail.log_.
Na podstawie punktu 1, podejrzewam, że przyczyną braku synchronizacji jest brak skonfigurowania listy FM w ustawieniach modułu.

Zachęcam użytkownika modułu do bezpośredniego kontaktu tutaj.

**Comment by pomocFM** [comment]
Panie Macieju, w takim razie na jaki adres email najlepiej odesłać tę osobę?

**Comment by mcjwsk** [comment]
Najlepiej, aby dyskusja toczyła się w tym miejscu.

**Comment by pomocFM** [comment]
Panie Macieju, niestety nie możemy udostępniać naszego firmowego loginu i hasła naszym klientom. Czy w takim razie klient może tworzyć własny login i hasło? Czy sprawy powinny jednak być opisywana z naszym pośrednictwem?

**Comment by mcjwsk** [comment]
Naturalnie miałem na myśli, aby każdy kto potrzebuje pomocy zakładał tutaj swoje WŁASNE konto. Jeżeli ktoś podejmuje się instalacji modułu, to tym bardziej powinien czuć się na siłach, aby używać Githuba ;).

**Comment by KarolinaBednarz** [comment]
Dzień dobry, prosiłabym o podanie konkretnego linku pod którym kliencie mogą zakładać własne zgłoszenia do Was :) Mamy klienta, który ma pilny problemi wolelibyśmy, żeby skontaktował się samodzielnie.

**Comment by mcjwsk** [comment]
https://github.com/SnowdogApps/FreshMail/issues/new

**Comment by KarolinaBednarz** [comment]
Dziękuję :) Dobrego dnia!
