### ISSUE TITLE
adresy wypisane z bazy Freshmail

### ISSUE THREAD

**Issue by aleksandrakrowicka** [SnowdogApps/FreshMail#5]
Szanowni Państwo, 

pisałam do supportu Freshmaila w sprawie wtyczki przeznaczonej dla mangento 1.x. Problem z jakim się borykam wygląda następująco: adres, który wypisze się z bazy poprzez Freshmail, po jakimś czasie wraca do  puli adresów aktywnych. Proszę o informację, co może być przyczyną i czy da się ten problem rozwiązać.

Aleksandra Krowicka

**Comment by mcjwsk** [comment]
Której wersji modułu używasz?

**Comment by aleksandrakrowicka** [comment]
z tej: https://freshmail.pl/wtyczka/magento/

**Comment by mcjwsk** [comment]
Niezbędna jest aktualizacja modułu do wersji [2.8.1](https://github.com/SnowdogApps/FreshMail/releases) oraz skonfigurowanie webhooka w ustawieniach modułu i na koncie FreshMail zgodnie z [opisem](https://github.com/SnowdogApps/FreshMail#webhooks)

Wykaz zmian pomiędzy wersją 2.6.13 a 2.8.1 można zobaczyć tutaj https://github.com/SnowdogApps/FreshMail/compare/2.6.13...2.8.1

**Comment by aleksandrakrowicka** [comment]
Dziękuję bardzo za pomoc :)
