### ISSUE TITLE
Popup na smartfonach.

### ISSUE THREAD

**Issue by pomocFM** [SnowdogApps/FreshMail#6]
Hej,

nasz Klient ma pytanie czy da się tak zrobić by Popup nie wyświetlał się na smartfonach, gdyż zasłania cały ekran. Wersja Magento 1.9

**Comment by mcjwsk** [comment]
Popup można wyłączyć w konfiguracji modułu od wersji 2.7.0 i wyższej.

**Comment by pomocFM** [comment]
Dzięki za informację :)
